feat(#237): implement app_status_advanced endpoint
fusion44/blitz_api pull request #238
Opened 2024-01-14 17:49 UTC by fusion44

Some apps might give status information that is computationally to expensive to include in the normal status endpoint which can be polled more often.

2024-01-22 14:26 UTC, cstenglein commented
Bugs: 
- Doesn't work if there is no appId specified (just loads forever).

2024-01-22 18:14 UTC, cstenglein requested changes
See above :)

2024-01-28 19:29 UTC, fusion44 commented
Changes:
* fix for wrong function calls
* returns `{ "initialSyncDone": false }` or `{ "initialSyncDone": false }` when called with `electrs` now
* clarified in endpoint documentation that the endpopint isn't implemented for all backends
* returns a `400 BAD REQUEST` when appID is invalid

2024-01-29 18:13 UTC, cstenglein commented
```
{
  "id": "electrs",
  "error": "script result processing error: /home/admin/config.scripts/bonus.electrs.sh status"
}

2024-02-18 10:33 UTC, cstenglein commented
When is this merged?

So I can merge the webui functionality as well ;)

2024-02-18 11:10 UTC, merged